language: python
dist: trusty
sudo: require
osx_image: xcode8.1
matrix:
  include:
  - os: linux
    env: CONDA=3.6
  - os: osx
    env: CONDA=3.6

cache:
  apt: true
before_install:
- |
  wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda${CONDA:0:1}-latest-$OS.sh
  bash miniconda.sh -b -p $HOME/miniconda
  export PATH="$HOME/miniconda/bin:$PATH"
  conda config --set always_yes yes --set changeps1 no
  conda config --add channels conda-forge
  conda update -q conda
  conda install -q conda-build
  conda create -q -n test-environment python=$CONDA
  source activate test-environment
install:
- conda build -c conda-forge conda.recipe
- chmod +x tools/upload_conda_package.sh
- tools/upload_conda_package.sh
script:
- echo "done"
notifications:
  email: false