package:
  name: samplebase
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - numpy
    - jsonpickle
    - pathos

  run:
    - python
    - numpy
    - jsonpickle
    - pathos

test:
  requires:
    - nose

about:
  summary: samplebase
  license_file: LICENSE
