name: samplebase_ci

on: [push, pull_request]

# Note ${{github.ref}} contains branch name when there is no tag and the tag name when there is a tag
jobs:
  samplebase_ci:
    name: samplebase_ci (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']#, 'macos-latest']#, 'windows-latest']
        python-version: ['3.6']#, '3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: prepare conda
        shell: bash -l {0}
        run: |
          tools/configure_conda.sh
      - name: build conda package
        shell: bash -l {0}
        run: conda build -c conda-forge conda.recipe
      - name: upload conda package
        # only build when upstream and on pushes
        # if GITHUB_REF has tag then package is uploaded to normal anaconda channel
        # if GITHUB_REF points to master then package is uploaded to dev channel
        if: github.repository == 'chrisfroe/samplebase' && github.event_name == 'push'
        env:
          BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        run: |
          tools/upload_conda_package.sh
